spring:
  application:
  name: customer-notification-service

server:
  port: 8086

logging:
  level:
    kafka: debug
    root: info
    db: info
    org.springframework.web: debug
    org.hibernate: error
    web: debug
